Module 8/objects/Product2/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Module 8/objects/Product2/fields/Quantity_Available__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Available__c</fullName>
    <label>Quantity Available</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Module 8/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>PurchaseOrderLineItem</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>PurchaseOrderLineItem Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Module 8/objects/PurchasedOrder__c/PurchasedOrder__c.object-meta.xml
<CustomObject>
    <label>PurchasedOrder</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>PO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PurchasedOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Module 8/objects/PurchasedOrder__c/fields/Order_Price__c.field-meta.xml
<CustomField>
    <fullName>Order_Price__c</fullName>
    <label>Order Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Module 8/objects/PurchasedOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Module 8/classes/ShoppingCartControllerTest.cls
@isTest
public class ShoppingCartControllerTest {
    @testSetup
    static void createProducts(){
        List<Product2> products = new List<Product2>();
        for(Integer i = 0; i < 5; i++){
            Product2 product = new Product2(Name = 'Product'+i, ProductCode = 'Code'+i, Price_Per_Unit__c = 20, Quantity_Available__c = 10);
            products.add(product);
        }
        insert products;
        
        List<PurchasedOrder__c> PurchasedOrders = new List<PurchasedOrder__c>();
        for(Integer i = 0; i < 5; i++){
            PurchasedOrder__c PurchasedOrder = new PurchasedOrder__c(Order_Price__c = 2*(i+1), Status__c = 'Pending');
            PurchasedOrders.add(PurchasedOrder);
        }
        insert PurchasedOrders;
    }
    @isTest
    static void testGetPurchasedOrders(){
        ShoppingCartController scc = new ShoppingCartController();
        List<PurchasedOrder__c> PurchaseList = scc.getPurchasedOrders();
        System.assertEquals(5, PurchaseList.size());        
    }
    @isTest
    static void testSortPurchasedOrderForOneTimeCalling(){
        ShoppingCartController scc = new ShoppingCartController();
        scc.sortPurchasedOrder();
        System.assertEquals('ASC', scc.sortDirection);        
    }
    @isTest
    static void testSortPurchasedOrderForTwoTimeCalling(){
        ShoppingCartController scc = new ShoppingCartController();
        scc.sortPurchasedOrder();
        scc.sortPurchasedOrder();
        System.assertEquals('DESC', scc.sortDirection);        
    }
    @isTest
    static void testSortProductForOneTimeCalling(){
        ShoppingCartController scc = new ShoppingCartController();
        scc.sortProducts();
        System.assertEquals('ASC', scc.sortDirection);        
    }
    @isTest
    static void testSortProductsForTowTimeCalling(){
        ShoppingCartController scc = new ShoppingCartController();
        scc.sortProducts();
        scc.sortProducts();
        System.assertEquals('DESC', scc.sortDirection);        
    }
    @isTest
    static void testAddItemTocart(){
        ShoppingCartController scc = new ShoppingCartController();
        scc.addItemTocart();
        System.assert(scc.renderCart);        
    }
    
    @isTest
    static void testGetWrapperCartProductsWhenTwoProductsSelected(){
        ShoppingCartController scc = new ShoppingCartController();
        List<WrapperProducts> wp = scc.getWrapperProducts();
        wp[0].selected = true;
        wp[1].selected = true;
        scc.addProductsToCart();
        List<WrapperCart> wc =  scc.getWrapperCartProducts();
        System.assertEquals(2, wc.size());    
        System.assert(scc.renderCart);             
    }
    @isTest
    static void testGetWrapperCartProductsWhenNoProductsSelected(){
        ShoppingCartController scc = new ShoppingCartController();
        List<WrapperProducts> wp = scc.getWrapperProducts();
        scc.addProductsToCart();
        List<WrapperCart> wc =  scc.getWrapperCartProducts();
        System.assertEquals(0, wc.size());     
        System.assert(!scc.renderCart);       
    }
    @isTest
    static void testProductQuantityWhenProductIsAddedToCartAndQunatityUnchanged(){
        ShoppingCartController scc = new ShoppingCartController();
        List<WrapperProducts> wp = scc.getWrapperProducts();
        wp[0].selected = true;
        scc.addProductsToCart();
        System.assertEquals(9, wp[0].quantity);     
    }
    
    @isTest
    static void testProductQuantityWhenProductIsAddedToCartAndQunatityChanged(){
        ShoppingCartController scc = new ShoppingCartController();
        List<WrapperProducts> wp = scc.getWrapperProducts();
        wp[0].selected = true;
        wp[1].selected = true;
        scc.addProductsToCart();
        List<WrapperCart> wc =  scc.getWrapperCartProducts();
        wc[0].productInCartQuantity = 4;
        scc.productId = wc[0].product.id;
        scc.updateCartQuantity();
        System.assertEquals(6, wp[0].quantity);   
    }
    @isTest
    static void testProductQuantityWhenProductIsAddedToCartAndDeleted(){
        ShoppingCartController scc = new ShoppingCartController();
        List<WrapperProducts> wp = scc.getWrapperProducts();
        wp[0].selected = true;
        wp[1].selected = true;
        scc.addProductsToCart();
        List<WrapperCart> wc =  scc.getWrapperCartProducts();
        wc[0].productInCartQuantity = 4;
        scc.productId = wc[0].product.id;
        scc.deleteProductFromCart();
        wc =  scc.getWrapperCartProducts();
        System.assertEquals(1, wc.size()); 
        System.assertEquals(10, wp[0].quantity);
    }
    @isTest
    static void testShowInvoice(){
        ShoppingCartController scc = new ShoppingCartController();
        scc.showInvoice();
        System.assert(!scc.renderCart);  
        System.assert(!scc.renderProductsTable);  
        System.assert(scc.renderInvoice);        
    }
    @isTest
    static void testGetInvoice(){
        ShoppingCartController scc = new ShoppingCartController();
        List<WrapperProducts> wp = scc.getWrapperProducts();
        wp[0].selected = true;
        wp[1].selected = true;
        scc.addProductsToCart();
        List<WrapperCart>  wc = scc.getInvoice();
        System.assertEquals(2, wc.size()); 
        System.assertEquals(40, scc.finalTotal);
    }
    @isTest
    static void testInsertedResultPurchasedOrderLineItem(){
        ShoppingCartController scc = new ShoppingCartController();
        List<WrapperProducts> wp = scc.getWrapperProducts();
        wp[0].selected = true;
        wp[1].selected = true;
        scc.addProductsToCart();
        List<WrapperCart>  wc = scc.getInvoice();
        scc.placeOrder();
        List<Purchase__c> p = [SELECT Id FROM Purchase__c];
        System.assertEquals(2, p.size()); 
    }
}